version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Cambia la contraseña según tu necesidad
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql          # Volumen persistente para los datos de MySQL
      - ./init-db:/docker-entrypoint-initdb.d # Inicializar la base de datos con archivos SQL
    networks:
      - app-network

  Restaurante:
    build:
      context: .
      dockerfile: Dockerfile
    image: alh7867/restaurante_api:v1.0
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:  # Volumen para los datos persistentes de MySQL

