# Server Port config
server:
  port: ${SERVER_PORT:8080}

# JDBC Properties for MySQL
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gammapedidos}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Alejandro2024}
    driver-class-name: com.mysql.cj.jdbc.Driver
